name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
        extensions: dom, fileinfo, gd, mbstring, exif
    - uses: actions/checkout@v4
    - name: Copy .env
      run: |
        cp .env.example .env
        sed -i 's/APP_DEBUG=.*/APP_DEBUG=true/' .env
        sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=sqlite/' .env
        sed -i 's/DB_DATABASE=.*/DB_DATABASE=:memory:/' .env
    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Run Migrations
      run: php artisan migrate:fresh --force
    - name: Install NPM Dependencies
      run: npm ci
    - name: Build Assets
      run: npm run build
    - name: Execute tests
      env:
        MAIL_MAILER: log
        QUEUE_CONNECTION: sync
      run: php artisan test
